name: Bangale Microservices CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build Products Microservice
      run: products-service/gradlew -p products-service build
    - name: Build Price History Microservice
      run: price-history-service/gradlew -p price-history-service build

